### ISSUE TITLE
Feature request: Display of stream url

### ISSUE THREAD

**Issue by uwe-ss** [louis77/tuner#101]
I would like to be able to copy the stream urls of discovered stations (for reuse elsewhere). An info window for stations similar to the one the competing "Shortwave" is offering would be nice.

**Comment by MechDR** [comment]
I'd also like to see this, this is a useful feature.

**Comment by louis77** [comment]
![image](https://user-images.githubusercontent.com/1240462/207992107-448e2120-a33c-427b-b62f-bbd5e3b7d3cc.png)

**Comment by ben2talk** [comment]
Compare with Shortwave - Context menu pulls up information listing Language, Tags, Votes, Location, Country, and finally:
Audio: Bitrate/Codec/Stream URL.

The Stream URL is important
