### ISSUE TITLE
Tuner makes no sound - Arch Linux

### ISSUE THREAD

**Issue by TwoClocks** [louis77/tuner#102]
I'm sure there is something wrong w/ my OS setup, but I need help figuring out what that is.

All the other apps I have that are supposed to make sound, do. Browsers, election apps, VLC etc. When they are playing audio, the apps show up in the "payback list" in the auto control app.

I'm running KDE on Arch Linux. I have pipewire, w/ all the pulse, alas, jack layers installed.

I've tried running tuner from the command line. No obvious errors come out. Nothing meaning in the system log.

Is there a verbose debug mode, or something? How can I figure out what API call is failing?

**Comment by tranzystorek-io** [comment]
Confirmed

**Comment by louis77** [comment]
Thanks for figuring this out! I've added a link to this issue in the README.
