### ISSUE TITLE
How to disable tracking by default?

### ISSUE THREAD

**Issue by Vascom** [louis77/tuner#105]
Hi.
I want add tuner to Fedora Linux repository.

How to disable in sources tracking by default?

**Comment by technosf** [comment]
Please elucidate your request.

**Comment by Vascom** [comment]
In settings I see tracking enabled by default.
How to make it disabled by default?

**Comment by technosf** [comment]
That is tracking on radio-browser - Probably needs better explanation. Tracking, I think, lets RB know if the station has had a play in a particular day. Could you LMK why you want to turn tracking off (just out of my own curiosity)?

Can add that to enhanced preferences behavior - can you add a comment [#77](https://github.com/louis77/tuner/issues/77) - if thats still an issue for you?

**Comment by Vascom** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2149834

**Comment by technosf** [comment]
> https://bugzilla.redhat.com/show_bug.cgi?id=2149834

I do not understand your point.

**Comment by Vascom** [comment]
I was asked to disable tracking by default.
As no such option at compile time I add patch for sources.

**Comment by technosf** [comment]
I see... I think if you want to add a note to #77 thats great and it can get dealt with there as part of implementing wider preferences

Closing this one. TY @Vascom
