### ISSUE TITLE
Station(s) radio with AAC+ 32kb  don't sounds

### ISSUE THREAD

**Issue by allexis-rapo** [louis77/tuner#108]
Please, I'm using tuner on Arch Linux, but the radio stations with AAC+ (32kb, 64kb...) don't sound. But radio stations with MP3 sound perfectly.
ES_CO: Yo estoy usando  la aplicación "tuner" en mi Arch Linux, pero las estaciones de radio con formato AAC+ no funcionan, pero las estaciones de radio con MP3 suenan perfectamente. Gracias por cualquier recomendación estimado @louis77

Thanks @louis77 from Colombia!!!

**Comment by technosf** [comment]
Related to [#44](https://github.com/louis77/tuner/issues/44) ?

**Comment by technosf** [comment]
Can you provide a Station where this is the case?

**Comment by technosf** [comment]
AAC work fine for me
