### ISSUE TITLE
Add a way to translate country names

### ISSUE THREAD

**Issue by NathanBnm** [louis77/tuner#11]
Maybe with a matching list?

**Comment by louis77** [comment]
I've found a free database of translated country names here: https://github.com/mledoze/countries
(see `countries.json`). 

Would you recommend to use PO to provide that country names or let the application handle the translation via a local mapping file?

**Comment by NathanBnm** [comment]
I think it would be fine to use this database but there are not all the available languages. Maybe there can be some file in the app, kind of an enumeration which makes the list in English and can be added to po files. What do you think?

**Comment by louis77** [comment]
Work on this has begun. With the commit 96f9407ac03e1117fa4f081a4550e449df21f857 there is a file /src/Models/Countries.vala which contains a map with all country names as translatable strings.

The list was generated from here:
https://datahub.io/core/country-list#data

**Comment by NathanBnm** [comment]
This can be closed according to #37 Don't know why it didn't close itself
