### ISSUE TITLE
Radio stations stop playing after 5 minutes

### ISSUE THREAD

**Issue by dtr125** [louis77/tuner#110]
The past couple of weeks in Garuda Linux I've experienced the radio stations keep stopping after 5 minutes of playing. I don't think it happens 100% of the time but seems to happen a lot and i have no idea why.

**Comment by technosf** [comment]
@dtr125 - is this still happening with v1.5.* ?

If so can you build Tuner locally and run it from the CLI and see what messages it spits out if/when it dies?

**Comment by dtr125** [comment]
I've been using ArcoLinux since I made this post, but Tuner has been
working fine on there.
