### ISSUE TITLE
Tuner won't open after upgrade to Mint 21.3 (Victoria) xfce 64-bit

### ISSUE THREAD

**Issue by ebpaul75** [louis77/tuner#111]
After reinstalling Mint 21.2 to my xfce laptop, and downloading the Tuner app from the Flatpack repository the app won't load.

wondering if there's a compatibility issue......Any advice would be helpful..

Thanks

**Comment by sand-clown** [comment]
I have the same problem. After installing Linux Mint 21.3 Virginia XFC or updating an older version, Tuner does not start. I tested it on several installations on different computers, and it doesn't work with the newer kernel either. It worked great on the previous version. I will be grateful for suggestions on what steps to take to find the problem. I'm sorry if I expressed myself incomprehensibly somewhere, I use Google translator.

**Comment by ebpaul75** [comment]
Actually I solved the problem; downloading the Louis Brauer, Tuner v1.4.0 app directly from the louis77/tuner repository located inGit Hub website.
WORKS GREAT!

**Comment by sand-clown** [comment]
In fact, the version installed from the website works properly. Thank you.

**Comment by technosf** [comment]
Flathub version is now 1.5.2 (latest)
Installs fine on Mint Cinnamon.
