### ISSUE TITLE
Tuner Theme Dark Mode does now work

### ISSUE THREAD

**Issue by nekrub2** [louis77/tuner#125]
When going into the preferences and selecting Theme Dark Mode nothing happens. Even after closing and restarting the application. 

I run Tuner v. 1.5.2  under Linux Mint 22

This no killer but I prefer Dark Mode.

**Comment by technosf** [comment]
I am running on the same OS, but i have dark but no light theme.

**Comment by nekrub2** [comment]
Here is a screenshot of Tuner

**Comment by nekrub2** [comment]
![Tuner_dark_mode](https://github.com/user-attachments/assets/a7e3eb9a-46f9-44b2-8e62-34ae3c7887a2)

**Comment by nekrub2** [comment]
![Linux_Setting_Themes](https://github.com/user-attachments/assets/4a96f046-694f-4ada-8bca-c6bdd8bcbd60)

**Comment by nekrub2** [comment]
In Linux Mint System Setting I explicitly let the application decide. Maybe I forced black mode it would become dark in Tuner.
