### ISSUE TITLE
Tuner will not start following updating to rev 1.5.4 using linux mint; latest release

### ISSUE THREAD

**Issue by ebpaul75** [louis77/tuner#144]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version and Installation Information**
- Found in version #:
- New, existing or recently updated Tuner install?

**If Tuner is Crashing or Hanging**
Start Tuner from the command line and post the output using the command:
```flatpak run com.github.louis77.tuner``` 

**OS & Desktop (please complete the following information):**

**Additional context**

**Comment by ebpaul75** [comment]
my system
Linux Mint 22 Kernel 6.8.0-47

**Comment by technosf** [comment]
@ebpaul75 
Can you try this and provide the output: `flatpak run com.github.louis77.tuner`
ty

**Comment by technosf** [comment]
Dupe - working on #142. Closing
