### ISSUE TITLE
WebradioDB compatibility as another open alternative server like Radio-Browser.info

### ISSUE THREAD

**Issue by goliv04053** [louis77/tuner#153]
**Is your feature request related to a problem? Please describe.**
This feature request is made because Radio Browser doesn't allow user editing radios information to fix when it's wrong or without complete informations. 

**Describe the solution you'd like**
Adding WedradioDB as another option to Radio Browser.

**Describe alternatives you've considered**
I considered using closed-source radio directory services apps, which limit flexibility and there is ads and those standard problems related to closed-source apps.

I also considered manually compiling radio links and using a media player like VLC, which is very time-consuming.

**Additional context**
His project and repo
https://github.com/jcorporation/webradiodb
https://jcorporation.github.io/webradiodb/

**Comment by technosf** [comment]
RadioBrowser was sort-of isolated from the App functionality, but I've cleaned it up and formalized.
In v1.6.*+ there is a Provider.API interface that any data provider can implement.
Initially the Provider implementation will be hard coded in the Application, RadioBrowser being the only provider.
When the API is release you can develop an implementation for WedradioDB and submit it.
