### ISSUE TITLE
libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.

### ISSUE THREAD

**Issue by gitbearflying** [louis77/tuner#166]
Hi,

since the switch to libsoup3, tuner crashes directly after execution with:
`libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.`

There is libsoup-2 installed in parallel(i can't remove it since other applications from my distro depend on it),
but ldd doesn't find that tuner is linked to it:

```
> ldd /usr/bin/tuner | grep -i soup
	libsoup-3.0.so.0 => /usr/lib64/libsoup-3.0.so.0 (0x00007fe88552f000)
```

 - OS: Slackware Linux
 - Version 15.0

How can i debug this? Where might the libsoup2 symols come from?

Thanks!

**Comment by gitbearflying** [comment]
Hi, not sure if i should open a new report, it's still the same error but at a different place...
I just build tuner 1.5.6 , now it starts normally, but crashes when selecting a station with the same error
`(tuner:2886): libsoup-ERROR **: 14:34:40.598: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.`

I'd be happy to test patches or whatever can help to debug this.

**Comment by technosf** [comment]
This is an issue with your system having both v2&v3 installed and the either the linker or the path to the libraries is mixed up.

Remove both libsoup libraries and files, and reinstall just v3. Look at the linker output to see where it is choosing v2 as well as v3.

This is not an issue with Tuner, and I do not have a system I could try and duplicate the situation. I would reach out to the Slackware community for help. Or, use the Flatpak.

Good luck!
