### ISSUE TITLE
Display current track info / artwork

### ISSUE THREAD

**Issue by neofight** [louis77/tuner#17]

**Comment by sysfu** [comment]
There are two stations, Hardradio & KNAC.com, for which I'm unable to view the track info for on their websites. It's also nice to be able to see this information directly in the player.

**Comment by louis77** [comment]
Hi @sysfu 
The track info is implemented and will be released in the next few days. Which OS are you running Tuner on?

**Comment by sysfu** [comment]
Nice! I'm running elementary OS 5.1.7 Hera

**Comment by louis77** [comment]
Version 1.3.0 was released with live track info and more. It's already available on Flathub, will soon be published on elementary AppCenter.
