### ISSUE TITLE
Arch Linux Support

### ISSUE THREAD

**Issue by btd1337** [louis77/tuner#18]
Hi @louis77, 

I will support your application in Arch Linux. 

Please

1. Consider to use 2 branchs: master (stable code), develop (development code).

2. Add a section containing the following instruction:

## Arch Linux
Arch Linux users can find `Tuner` under the name [tuner-git](https://aur.archlinux.org/packages/tuner-git/) in the **AUR**:

```sh
$ yay -S tuner-git
```

**Comment by louis77** [comment]
Thanks @btd1337 for picking up Tuner for Arch Linux. 
I've added remarks in the README.md and Credits to you. I've installed Tuner on Arco Linux and it looks like some elementary OS-native icons are missing. I'll go into that and try to replace them or add them into the package. Also the dark theme doesn't look too well yet.

**Comment by louis77** [comment]
Dark theme and missing icons should now be fixed.
