### ISSUE TITLE
Changes required for AppCenter: OARS Social Info, Release Description

### ISSUE THREAD

**Issue by cassidyjames** [louis77/tuner#2]
Thanks for submitting your app to AppCenter! However, while reviewing the submission, we found a couple of issues that need to be resolved.

- [x] Since your app uses an external web service, its `social-info` value **must** be set to `mild` or higher, depending on the data that is sent. You can always ensure your OARS data is correct by using the [official OARS generator](https://hughsie.github.io/oars/).

    https://github.com/louis77/tuner/blob/6469d9bc660d93b232bb20bf9321999caaf3ec1f/src/Services/RadioBrowserDirectory.vala#L111
    https://github.com/louis77/tuner/blob/ea46643d0c2b03041ce3e5ddebbc25a068e12239/data/com.github.louis77.tuner.appdata.xml.in#L35-L48

- [x] Updates must include accurate [release descriptions](https://docs.elementary.io/develop/appcenter/publishing-updates#release-descriptions). Please detail the user-facing changes in the proper tag. You can include the 1.2.0 details in the next version's release description (i.e. 1.2.1) since 1.2.0 will have never reached users.

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). As always, if you have any questions you can reply here.

**Comment by louis77** [comment]
OARS and AppStream release descriptions updated for 1.2.1

**Comment by cassidyjames** [comment]
@louis77 be sure to log into the [AppCenter Dashboard](https://developer.elementary.io/dashboard) and re-submit the release if you have not already.

**Comment by louis77** [comment]
@cassidyjames Re-submitted release 1.2.3 with many improvements.

**Comment by cassidyjames** [comment]
@louis77 great! I see it in the queue. Someone will take a look soon. :)

**Comment by cassidyjames** [comment]
@louis77 just a note: 1.2.3 has been accepted and released to users! You should see it roll out to AppCenter on elementary OS and the web shortly.
