### ISSUE TITLE
Favorites can't be saved unless the file .local/share/com.github.louis77.tuner/favorites.json exists already

### ISSUE THREAD

**Issue by emulti** [louis77/tuner#20]
With the Arch AUR package it's necessary to manually create the file .local/share/com.github.louis77.tuner/favorites.json after the package is installed, or starred stations can't be saved.

**Comment by louis77** [comment]
Thanks for bringing this up. I've fixed it. Can you check that it works now on your machine? (still have to do some Arch setup here)

**Comment by emulti** [comment]
yes, that works- favorites.json is created if it doesn't already exist
Thanks!
By the way, here is a screenshot of how Tuner looks with the Adwaita-Dark theme, so you can see the problem area.
![Screenshot from 2020-08-04 23-50-26](https://user-images.githubusercontent.com/7505390/89353084-9377a700-d6ad-11ea-86d1-87fb10fe7577.png)
