### ISSUE TITLE
Adwaita Dark Theme support

### ISSUE THREAD

**Issue by louis77** [louis77/tuner#21]
By the way, here is a screenshot of how Tuner looks with the Adwaita-Dark theme, so you can see the problem area.
![Screenshot from 2020-08-04 23-50-26](https://user-images.githubusercontent.com/7505390/89353084-9377a700-d6ad-11ea-86d1-87fb10fe7577.png)
Mouse is over 'Kiss FM Ro' which makes it highlight.

_Originally posted by @emulti in https://github.com/louis77/tuner/issues/20#issuecomment-668864352_

**Comment by louis77** [comment]
Fixed in d0b44300ac70d71d477b89577ed76a8c522a9473

**Comment by emulti** [comment]
Tested an Arch AUR build from the 'develop' branch: looks good!
