### ISSUE TITLE
AppData screenshot shows inappropriate station

### ISSUE THREAD

**Issue by hadess** [louis77/tuner#26]
Info Wars isn't really appropriate material to show in a screenshot:
https://raw.githubusercontent.com/louis77/tuner/master/docs/screen_light_1.2.4.png

It's already been removed from Facebook, Apple, Spotify, YouTube, and Vimeo. See:
https://en.wikipedia.org/wiki/InfoWars#Removals_from_other_websites

**Comment by louis77** [comment]
Thanks for bringing this up. I didn't realize all the unsettling controversy around info wars, never listened to it.
I'll have it removed asap.

**Comment by louis77** [comment]
Screenshot replaced in current version 1.3.0.
Published on Flatpak, elementary AppCenter will follow soon.
