### ISSUE TITLE
Turkey radio not working 

### ISSUE THREAD

**Issue by safak45x** [louis77/tuner#30]
![2020-09-24 08 15 17 ekran görüntüsü](https://user-images.githubusercontent.com/59151376/94103809-26c39200-fe3e-11ea-817d-35572e4099c1.png)
Most do not work please update

**Comment by louis77** [comment]
Is it just "TRT Nagme" that is not playing or are there more?
With TRT Nagme I could reproduce the issue however, all the others are working.
Would be great if you could tell me some more stations that don't work (1-2 more).

**Comment by louis77** [comment]
Just some research. It looks like _TRT Nagme_ has a strange bitrate:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=143236,CODECS="mp4a.40.2"
chunklist_w2017485907.m3u8
```

According to http://www.radio-browser.info/gui/#!/history/9a5df56c-7979-4a1c-b232-9032d26f00f2 it seems to change sometimes.

**Comment by safak45x** [comment]
until tomorrow I will write the names of non-working stations as a list here.

**Comment by safak45x** [comment]
> Oynamayan sadece "TRT Nagme" mi yoksa daha fazlası mı var? 
> TRT Nagme ile konuyu yeniden üretebildim ancak diğerleri çalışıyor. 
> Bana çalışmayan birkaç istasyon daha söylerseniz harika olur (1-2 tane daha).

There are many stations not working

**Comment by safak45x** [comment]
Not Working Staions

1 HaberTurk
2 Ahaber
3 TRT Arabic TV
4 TRT Radyo 3
5 TRT Music TV
6 TRT Radyo 1
7 Alem FM

Stations Add 

1 Cnn Türk Radyo
2 Number One Türk
3 Number One Türk Slow
4 Efkar FM
5 Diyanet Radyo

**Comment by safak45x** [comment]
I wonder if your studies on this subject continue

**Comment by NathanBnm** [comment]
@safak45x web radios listed in the app are provided by https://www.radio-browser.info/#!/ so maybe you can address them an issue for web radios that doesn't work properly. You can also suggest new radios here : https://www.radio-browser.info/#!/add

**Comment by louis77** [comment]
I've rechecked the stations @safak45x was providing and they all worked. I'm closing this issue for now.
Feel free to reopen if there are still issues.
