### ISSUE TITLE
Old starred stations stuck as favorites

### ISSUE THREAD

**Issue by NathanBnm** [louis77/tuner#38]
I added some stations to favourites before that you changed the favourite system with the json file. But now I can't remove them from favourites and when I add them back to favourites they appear twice.

**Comment by louis77** [comment]
Thanks @NathanBnm for bringing this up. I can confirm this issue, I had it myself but neglected to fix it :-)
Which distro do you use?

**Comment by NathanBnm** [comment]
I'm using elementary OS

**Comment by technosf** [comment]
Confirming Faves in 1.5 are inconsistent if staring/unstaring
