### ISSUE TITLE
Main Window not resizable

### ISSUE THREAD

**Issue by DasJott** [louis77/tuner#41]
I just installed the app and immediately noticed, that the window is not resizable. That is somehow odd.

Using Manjaro Linux, was installing the Flatpak version.

**Comment by DasJott** [comment]
Just tried the version from AUR and that one works perfectly fine.

**Comment by louis77** [comment]
@DasJott Thank you for your bug report, please apologize my late response. I could reproduce the issue from Flatpak. No clue yet why this happens.

**Comment by Henryws** [comment]
https://github.com/louis77/tuner/blob/2247ba44dce9bb9a46e90dab7f0f3ddcae2e164d/src/Widgets/Window.vala#L109

Perhaps this?

**Comment by technosf** [comment]
Window  is resizeable.
