### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by jwisbell50** [louis77/tuner#43]
Linux MInt 20.1 Cinnamon. Kernel 5.4.0-65-generic. Really like the program but it needs some kind of volume control.

**Comment by louis77** [comment]
Thank you for your feedback. I will consider this for the next release.

**Comment by louis77** [comment]
Volume control is coming...

![Screenshot from 2021-05-02 00-44-51](https://user-images.githubusercontent.com/1240462/116796796-abb31000-aadf-11eb-9235-458bd5537438.png)

**Comment by louis77** [comment]
That is now fixed with [version 1.4.0](https://github.com/louis77/tuner/releases/tag/1.4.0).
