### ISSUE TITLE
[Flatpak] AAC+ Streams not decoding properly

### ISSUE THREAD

**Issue by MarshmelloSUCKS** [louis77/tuner#44]
I'm having an issue with AAC High Efficiency streams where the regular AAC audio decodes fine but high efficiency never kicks in. [Here's an example](https://msx.gay/random/example.ogg) with the first clip being from Tuner and the second clip being from Shortwave, both playing the same stream.

This issue only seems to affect Flatpak builds, decoding of AAC+ streams works properly when built from source.

**Comment by melomane63** [comment]
this stream ( aac+ ) not play in Tuner ( flatpak 1.40)  
http://91.121.65.189:8000/zinzine-AAC

work in firefox and shortwave

**Comment by docop** [comment]
While i can add, appimage could also be something great to have .. The app is quite nice and video or east europe are nice addition. Thanks
