### ISSUE TITLE
does not preserve dark appearance (dark mode)

### ISSUE THREAD

**Issue by aliskinr** [louis77/tuner#47]
uname -a
Linux mbs 5.11.101 #2 SMP Thu Mar 25 20:33:19 EET 2021 x86_64 x86_64 x86_64 GNU/Linux

sysinfo https://i2.paste.pics/df923fde26b2738431bbb81a05d1bcf8.png

video https://youtu.be/ipNGK4ZOLlo

![Screenshot_20210413_094122](https://user-images.githubusercontent.com/82435321/114508439-07a31b00-9c3d-11eb-8d74-69e66dffe119.png)

+the window title is not displayed on the taskbar

**Comment by louis77** [comment]
Thanks for your perfect bug report!
That will be fixed in the next release (1.4).

**Comment by louis77** [comment]
That is now fixed with [version 1.4.0](https://github.com/louis77/tuner/releases/tag/1.4.0).

**Comment by aliskinr** [comment]
closed by me. 

**in version 1.4.0 its fixed,**
