### ISSUE TITLE
Display more details in the search results

### ISSUE THREAD

**Issue by edomont77** [louis77/tuner#48]
Hi. It would be great if more details were returned in the search results.
I mean, apart from the station name and country, other details like the n. of vote, stream info and other tags that are included in the Radio Browser catalog.
In this way stream with identical names but different formats or quality could be easily identified.

For example: when you search "swiss jazz", there are stations with the same name, but they use MP3, AAC, etc.
https://www.radio-browser.info/#!/byname/swiss%20jazz

Thanks.

**Comment by louis77** [comment]
@edomont77 Thanks for your great suggestion! I've just added Coded and Bitrate on a local dev version and it makes a lot of sense. I'm going to hack a little on the design and release this soon.

**Comment by edomont77** [comment]
Hi louis77

Looks great!

Looking forward for playing with the next update :-)

Thanks.


edo

Apr 30, 2021 9:58:55 PM Louis Brauer ***@***.***>:

**Comment by louis77** [comment]
That is now implemented with [version 1.4.0](https://github.com/louis77/tuner/releases/tag/1.4.0).

**Comment by edomont77** [comment]
Hi louis77.
Thank you!
Waiting for this to be included into Arch Linux AUR.
