### ISSUE TITLE
Use gnome theme

### ISSUE THREAD

**Issue by smalltimer** [louis77/tuner#52]
Hi, 

First up, this is fantastic software. Thank you for the time and effort that has been invested in this project!

I was wondering if it is at all possible to make the top bar follow the gnome/gtk theme. Right now, the buttons on the top-left do not follow the system theme, and full-screening has no effect. For reference, I am attaching snapshots in floating and fullscreen mode for tuner and audacious (a software which follows the system theme). 

* Audacious: floating
![audacious-floating](https://user-images.githubusercontent.com/14436654/116053528-1517c680-a67b-11eb-91a9-e18d77f6204c.png)

* Audacious: fullscreen
![audacious-fullscreen](https://user-images.githubusercontent.com/14436654/116053532-1648f380-a67b-11eb-8cfd-cd2a0bfb1a33.png)

* Tuner: floating
![tuner-floating](https://user-images.githubusercontent.com/14436654/116053533-16e18a00-a67b-11eb-8542-5bb7344b52e5.png)

* Tuner: fullscreen
![tuner-fullscreen](https://user-images.githubusercontent.com/14436654/116053534-16e18a00-a67b-11eb-9e42-d1cc30e51068.png)

Please feel free to remove this message if this is not the right forum for it. If this is the case, I'd like to know the right place for this discussion please.

Cheers!

**Comment by BzfpWg9g** [comment]
Workaround: https://github.com/PCMan/gtk3-nocsd. Installing procedure depends on your OS

**Comment by smalltimer** [comment]
Thanks for the response @BzfpWg9g - had no idea `gtk-nocsd` existed! I'm on Debian 10 and I installed it right from the repo. But unfortunately can't figure out how to get the nocsd to work with flatpak. Any tips? Couldn't find too many answers by googling.

**Comment by BzfpWg9g** [comment]
Sorry, @smalltimer, no experience with flatpk but there should be deb file in normal repository. After installing try adding this to `~/.profile`

`export GTK_CSD=0`
`export LD_PRELOAD=/usr/lib/libgtk3-nocsd.so.0`

Maybe you need to reboot/logout afterwards. I know I had some difficulties getting this to work but can't remember the steps.

**Comment by smalltimer** [comment]
Hi again, do you mean this repo for tuner has a .deb too? I can't seem to be able to find it.

**Comment by BzfpWg9g** [comment]
Ah I understand. You installed Tuner via flatpak and gtk3-nocsd via deb. No, unfortunately there is no deb for Tuner (as far as I know). Did you try adding the 2 lines in `~/.profile`? Did it work? 

If not maybe flatpak, snap, etc. behave differently than regular installations. I built Tuner from source so I can't tell. If you want to check if gtk3-nocsd is working you could try installing some regular application which uses client side decorations, e.g.. gnome-mahjongg.

**Comment by smalltimer** [comment]
With Debian you can install `gtk3-nocsd` systemwide so there's no need to include it in `.profile`. I tested it with gnome to-do and it works. 

Regarding tuner: I don't understand why CSD cannot be left alone In any case, the software works. It's just ugly on most operating systems! Leaving this open in case someone comes up with a trick to make `gtk3-nocsd` work with flatpak.

**Comment by BzfpWg9g** [comment]
I read some pages about flatpak now and it seems the applications are isolated from the rest of the system. Stumbled across this site: https://githubmemory.com/repo/kujeger/flatpak-gog/issues 

`flatpak run com.gog.PrisonArchitect`
`ERROR: ld.so: object '/home//.var/app/com.spotify.Client/libgtk3-nocsd.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`Running Prison Architect`
`ERROR: ld.so: object '/home//.var/app/com.spotify.Client/libgtk3-nocsd.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

You could try to find out the folder for Tuner, maybe something like `/home//.var/app/com.github.louis77.tuner/` and putting `libgtk3-nocsd.so` there (if the folder is persistent).
