### ISSUE TITLE
Chrash when selecting Favorites

### ISSUE THREAD

**Issue by wamukota** [louis77/tuner#53]
When selecting favorites  the program crashes.
System:
I am running ArchLinux and installed the AUR-version. My locale is Dutch. DE is Gnome 40.0
Situation:
As soon as I select Favorites, the program chrashes. All the other options in the Selections and Genres work without a problem.
What I tried:
First I thought it was a syntax error in the favorites.json file. I deleted that file and when I restarted Tuner and clicked on Favorites, the program crashed.
Workaround:
I have been able to get into the favorites by first selecting my country - Belgium - then playing a random station and then clicking on the Favorites.  Any other sequence of actions (first selecting the popular or the trending sets) leads to a crash when clicking on Favorites.

Alain

**Comment by louis77** [comment]
@wamukota Thank you very much for your bug report! I'll look into this.

**Comment by technosf** [comment]
@wamukota -  Is this still an issue with the 1.5.* releases?
