### ISSUE TITLE
No title in\on taskbar

### ISSUE THREAD

**Issue by aliskinr** [louis77/tuner#54]
https://github.com/louis77/tuner/issues/47
Я это не считаю страшной проблемой.
I don't think this is a terrible problem.
---
https://youtu.be/Nc03C4KD6jQ

**Comment by aliskinr** [comment]
??? hm-m... It`s ubuntu **18**.04 https://i2.paste.pics/df923fde26b2738431bbb81a05d1bcf8.png

I do not spam screenshots?

![Screenshot_20210511_194650](https://user-images.githubusercontent.com/82435321/121418330-82559180-c973-11eb-975f-1da5cc3823db.png)

**Comment by aliskinr** [comment]
I think (I sure of 99.99%) that it is related to https://github.com/louis77/tuner/issues/49 

???

**Comment by louis77** [comment]
That is now fixed with [version 1.4.0](https://github.com/louis77/tuner/releases/tag/1.4.0).

**Comment by louis77** [comment]
Duplicate of #49

**Comment by aliskinr** [comment]
I do not want to be harmful, but I did not work. I do not know what division, and what integers % :))

I don't want to create another branch "bugs". Most likely, I did something wrong.
`
Build started at 2021-06-10T02:56:56.223000
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.45.1
Source dir: /home/xuser/dnl/tuner-1.4.0
Build dir: /home/xuser/dnl/tuner-1.4.0/build
Build type: native build
Project name: com.github.louis77.tuner
Sanity testing C compiler: cc
Is cross compiler: False.
Sanity check compiler command line: cc /home/xuser/dnl/tuner-1.4.0/build/meson-private/sanitycheckc.c -o /home/xuser/dnl/tuner-1.4.0/build/meson-private/sanitycheckc.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/xuser/dnl/tuner-1.4.0/build/meson-private/sanitycheckc.exe
Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
Running compile:
Working directory:  /tmp/tmp1aa1x0ps
Command line:  valac /tmp/tmp1aa1x0ps/testfile.vala -C -C -o /tmp/tmp1aa1x0ps/output.obj 

Code:
 class MesonSanityCheck : Object { }
Compiler stdout:
 Compilation succeeded - 1 warning(s)

Compiler stderr:
 warning: --output and -o have no effect when -C or --ccode is set

Native Vala compiler: valac (valac 0.40.23)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency glib-2.0 found: YES 2.56.4
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency glib-2.0 found: YES 2.56.4
Determining dependency 'gtk+-3.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gtk+-3.0 found: YES 3.22.30
Determining dependency 'gee-0.8' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gee-0.8 found: YES 0.20.1
Determining dependency 'gio-2.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gio-2.0 found: YES 2.56.4
Determining dependency 'granite' with pkg-config executable '/usr/bin/pkg-config'
Native dependency granite found: YES 0.5
Determining dependency 'gstreamer-1.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gstreamer-1.0 found: YES 1.14.5
Determining dependency 'gstreamer-player-1.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency gstreamer-player-1.0 found: YES 1.14.5
Determining dependency 'libsoup-2.4' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libsoup-2.4 found: YES 2.62.1
Determining dependency 'json-glib-1.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency json-glib-1.0 found: YES 1.4.2
Determining dependency 'libgeoclue-2.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libgeoclue-2.0 found: YES 2.4.7
Determining dependency 'geocode-glib-1.0' with pkg-config executable '/usr/bin/pkg-config'
Native dependency geocode-glib-1.0 found: YES 3.25.4.1

data/meson.build:35:0: ERROR: Division works only with integers.

`

**Comment by louis77** [comment]
Looks like you have an older version of meson. I've changed the meson.build file a bit. 
Can you please `git pull` and try to compile again?

**Comment by aliskinr** [comment]
@louis77 , I do not consider this a mistake. This is a compilation error.
When I installed dependencies to compile, then a lot of "extra" packages was established. Then I had to spend some time to remove these packages. I compiled on real gland. It was enough to do everything in a virtual machine.

Yes, maybe (most likely) this is due to the version of the Mason or something else.

I don't want to compile once again on real hard.

I will try in a virtual machine.

And this ... I want to do the localization of the tuner into Russian and Ukrainian. But I do not quite understand how to do it. Once upon a time, I have tried to localize some kind of program for Windows. I do not remember what and how.
---
I do not know how to use GIT. Although there is nothing complicated in this, but I do not know how.
---
I hope the gagloperevod translates correctly what i wrote **here and now**.

**Comment by aliskinr** [comment]
I continue in this topic: 

still not working :) But these are just an error when assembling. https://youtu.be/-HCA7zSdXAU

https://drive.google.com/file/d/1F5L96Gsj-EBNtFcam39ZklZmRjM-OiDB/

**Comment by aliskinr** [comment]
**Louis Brauer, where are you?**

**Comment by domenicoguerra** [comment]
install **gettext** , it is necessary for traslation, but not in the dependency list. after recompile

**Comment by aliskinr** [comment]
ok, but not now.

 Now I am busy with my magic blog service. He is already tired of %: ((

**Comment by aliskinr** [comment]
closed by me
