### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by domenicoguerra** [louis77/tuner#56]
in flatpak, tuner 1.4 is not translated in my language ( french)

Compiled from sources, tuner was not translated also. 

after installation of gettext ( not in the list of dependencies)  and recompiled,   translation is ok.
OS Debian 11

**Comment by aliskinr** [comment]
The application is translated into French. But obviously there are some misunderstandings in the code.

I translated the application (at my localhost) into Russian.
Compiled.
I wanted to test the Russian translation to finish. 
But it is impossible to test different translations. 

I have already informed the author 
https://github.com/louis77/tuner/issues/54

**Comment by domenicoguerra** [comment]
yes , gettext is necessary to have traslation. 
Gettext isn't in the dependency list. 

for flatpak, it is possible than it is the same problem.

**Comment by louis77** [comment]
Hi guys, thank you very much for our contributions. I didn't realize that gettext is not installed by default on every Linux OS. 
Btw. Tuner doesn't "compile" in a specific language. It is translated runtime. So if you want to run Tuner in a different language than your OS, you can just do this:

`$ LANGUAGE=fr com.github.louis77.tuner`

Then you should see Tuner in French. Can you please try it?

**Comment by domenicoguerra** [comment]
@louis77 , tuner is in french here, after install gettext and redo Building
i have tried , for exemple $ LANGUAGE=it com.github.louis77.tuner, tuner is in italian. 

flatpak's tuner is not translated

**Comment by aliskinr** [comment]
Understandably. It's all about **gettext** .

Unfortunately, I can't test and finish the Russian translation in this period. I have my own "trouble".
Later, something must be informed.

The code in Ubuntu 18.04 is still not compiled. I already wrote about it somewhere around here.
