### ISSUE TITLE
Update screenshots for OS 6

### ISSUE THREAD

**Issue by danrabbit** [louis77/tuner#60]
The new release of Tuner is looking great and almost ready to publish! https://github.com/elementary/appcenter-reviews/pull/72

The only thing I'm noticing is it looks like your screenshots need to be updated for OS 6 and then we're good to go :)

**Comment by krisives** [comment]
Here are some for ya if you need @louis77 

![Screenshot from 2021-08-13 10 59 26](https://user-images.githubusercontent.com/153967/129404273-9416fd6f-49f9-4b43-85ce-a7cbef16e4f4.png)
![Screenshot from 2021-08-13 11 33 38](https://user-images.githubusercontent.com/153967/129404276-022e7c19-59cb-448b-8cf3-2fda7277daaa.png)
![Screenshot from 2021-08-13 11 34 17](https://user-images.githubusercontent.com/153967/129404279-fa09bb78-a386-4554-a509-031e0c267110.png)
![Screenshot from 2021-08-13 11 34 51](https://user-images.githubusercontent.com/153967/129404280-d26e3b1f-1795-4895-bcce-42f7844bd3f4.png)
![Screenshot from 2021-08-13 11 35 09](https://user-images.githubusercontent.com/153967/129404282-7db9c255-5e8f-4a68-b908-54e61dc8a886.png)
![Screenshot from 2021-08-13 11 35 14](https://user-images.githubusercontent.com/153967/129404283-0555e1e6-d5a1-49c2-b206-b67a757a0c5b.png)
![Screenshot from 2021-08-13 11 35 45](https://user-images.githubusercontent.com/153967/129404284-ba32ad20-7d54-403e-acdc-5f1892889f46.png)
![Screenshot from 2021-08-13 11 35 49](https://user-images.githubusercontent.com/153967/129404286-dc41c6c0-3cda-4e1f-af31-a065ce54f5fa.png)

**Comment by louis77** [comment]
Thank you @krisives , I've integrated the screenshots in the current release.
