### ISSUE TITLE
Multiple `default` screenshots

### ISSUE THREAD

**Issue by cassidyjames** [louis77/tuner#62]
It looks like you accidentally marked multiple screenshots as `default` in your latest AppData update.

https://github.com/louis77/tuner/blob/3ed75fec1b85d1b572f70b34a65a1897357e8424/data/com.github.louis77.tuner.appdata.xml.in#L27-L32

**Comment by louis77** [comment]
@cassidyjames fixed, do you need a new release tag?

**Comment by cassidyjames** [comment]
@louis77 it looks like it's passing in CI, but a new tag would be ideal to avoid any potential issues.
