### ISSUE TITLE
Dark mode and Sort by 

### ISSUE THREAD

**Issue by hugovelasco** [louis77/tuner#63]
I'd like to report that dark mode is not working apparently, or it's not working on linux mint mate 20.02 at least, and it would be amazing if we could filter/sort radios by country or language.
Thanks for the initiative anyway.

**Comment by louis77** [comment]
Hi @hugovelasco, thanks for reporting!
Could you indicate which version of Tuner you are running and how installed it (Flathub, Pacstall etc.)?

**Comment by hugovelasco** [comment]
I've been using Tuner v1.4.0 from flathub ;)

**Comment by FinixFighter** [comment]
I'd also love to search for station by country or language! +1! ^^
