### ISSUE TITLE
Memory leak caused maxxed out RAM in Macbook Air and Element OS

### ISSUE THREAD

**Issue by jaleelbeckjrc** [louis77/tuner#71]
Happened to download this app for Element OS through its app store. Element OS replaced the MacOS on an older Macbook Air with just 2M of RAM.  I watched the memory specs when switching to a different music category.  When I visited "House", the RAM started climbing by several MB every few seconds. I figured that this was normal having loaded new station icons. However it kept climbing until RAM was at 97% capacity.

Before I tried checking memory, the app locked up the computer. It seems something is causing the memory to leak under this environment.

**Comment by Henryws** [comment]
Have you tried the non flatpak version? Does that give a memory leak?

**Comment by technosf** [comment]
@jaleelbeckjrc - Is this still an issue?
