### ISSUE TITLE
Include 'Now Playing' info (D-Bus MPRIS)

### ISSUE THREAD

**Issue by Norimaki** [louis77/tuner#72]
Please consider including at least one field in the mpris metadata to indicate what is currently playing.

Something like .metadata["tuner.nowplaying"] (like vlc ["vlc.nowplaying"])

Although maybe it would be better to have:

"xesam: title" = player.nowplaying ("York - Farewell To The Moon)
"xesam: artist" = station.title ("Amb2FM") 

and not

"xesam: title" = "Tuner"
"xesam: artist" =  station.title

**Comment by heldderarbeit** [comment]
Hello, this is a feature I would love to see. Right now, the Wingpanel Sound Indicator panel is a bit empty (compared for example with the default Elementary music app):

![Screenshot from 2021-11-20 03-46-28](https://user-images.githubusercontent.com/4840355/142713140-c9800d46-5fbd-4089-b52d-a82584aab753.png)

I have no prior experience with Vala, but I hacked something together that - kinda - shows what could be a possible goal here:

Before

![Screenshot from 2021-11-20 04-00-39](https://user-images.githubusercontent.com/4840355/142713184-62c5d087-dbb3-4126-b76f-3cf496a5ca5a.png)

After

![Screenshot from 2021-11-20 04-22-35](https://user-images.githubusercontent.com/4840355/142713187-53aac8a7-f7af-4117-a9e9-8627824795c2.png)


In DBusMediaPlayer.vala
```
public HashTable<string, Variant>? metadata {
   owned get {
      var table = new HashTable<string, Variant> (str_hash, str_equal);
      var playerController = Application.instance.player;
      var media_info = playerController.player.get_media_info();
      table.insert ("xesam:title", playerController.extract_title_from_stream(media_info));
      var station = Application.instance.player.station;
      if (station != null) {
         var station_title = station.title;
         var favicon_url = station.favicon_url;
         table.insert ("xesam:artist", get_simple_string_array (station_title));
         table.insert ("mpris:artUrl", favicon_url);
      } else {
         table.insert ("xesam:artist", get_simple_string_array (null));
      }
      return table;
   }
}
```

Now, the major problem with this construction is that song changes don't get reflected in the sound indicator area - The title is updated automatically in the main window of the app, but not outside of that. Does anyone know how to fix that?
![Screenshot from 2021-11-20 05-09-50](https://user-images.githubusercontent.com/4840355/142714052-5fb914f9-ac9e-412b-b72e-bad60a8665e3.png)

**Comment by Norimaki** [comment]
Hi, I have been working on mpris. You can see my progress here:
https://github.com/Norimaki/tuner/tree/master-mpris-wip

It's not finished but it should be works. 

Regarding Wingpanel: I'm developing under xfce with xfce4-pulseaudio-plugin but maybe it's related.

I also had problems.
The main issue was the plugin expects to receive a Variant of type String  (pulseaudio-mpris-player.c::player->title = g_strdup(g_variant_get_string(value, NULL));) but get_simple_string_array() does not send it.

**Comment by technosf** [comment]
Done
