### ISSUE TITLE
All my station favorite and radio don't play anymore for no reasons

### ISSUE THREAD

**Issue by tr1p0p** [louis77/tuner#76]
Last version, on Fedora 35 with flatpack for some reasons (??) ALL the radio (except one ?) not working and don't want to play anymore at all, click on it don't work.

Why it's so hard to have a proper... web radio player that work on linux ? (this old thing that exist since the dawn of internet). That make the program not usable like this for no reason, very frustrating

**Comment by ismaail** [comment]
@tr1p0p What version are u using and what Stations that don't play anymore  ?

version `v1.5.0` works fine for me on ArchLinux.

**Comment by tr1p0p** [comment]
Using the flatpak one, well like all my favorite was some radio like NTS, Fip, Alternative Radio, Fip Groove. Stuffs like that.

**Comment by rogueanx9** [comment]
@ismaail Hi, can you tell me what the exact step do you use to install this? I am using yay atm and the app seems can't play any radio station. I am using pipewire as audio server if it does help.

**Comment by ismaail** [comment]
@rogueanx9 I installed **tuner-git** version **1.5.0**

![image](https://user-images.githubusercontent.com/4411670/154852434-0f705f3e-9d15-4557-a276-f6504960864e.png)


try `yay -S tuner-git`

![image](https://user-images.githubusercontent.com/4411670/154852267-493649de-87d1-44f2-942f-e6907252d576.png)

**Comment by technosf** [comment]
@tr1p0p - Is this still an issue?
