### ISSUE TITLE
Preferences - was 'Starting Screen' 

### ISSUE THREAD

**Issue by alasta4204** [louis77/tuner#77]
Many thanks for your hard work to date on this .Is it possible to have the app start up with the "starred stations" displayed ?
![Screenshot from 2022-01-02 19-00-36](https://user-images.githubusercontent.com/44087152/147886604-b0a87891-1d6f-457a-90a8-3dc857699803.png)

Many thanks

**Comment by technosf** [comment]
Enhanced preferences to set this behavior needed.

**Comment by technosf** [comment]
Done , v2
