### ISSUE TITLE
favorites not saving when closing tuner

### ISSUE THREAD

**Issue by ktr2022** [louis77/tuner#78]
Hi,

I am running elementary OS 6.1 and installed tuner from AppCenter. I have a little issue with favorites. Selection of favorites works well but the app doesn't save them.

Usually, I would expect the data in the directory ~/.var/app/com.github.louis77.tuner/data/ but in this case it is empty: no file favorites.json appears there.

I already uninstalled the app, removed all tuner related files in my $home and installed it again but the behaviour is the same.

On the other side, I checked this on a VM based elementary OS 6.1. - and there everything works well.

I really would appreciate to have my favorites stored. Do you have any suggestion for me?

Best regards,
Klaus

**Comment by actionless** [comment]
> Usually, I would expect the data in the directory ~/.var/app/com.github.louis77.tuner/data/ 

i have it at `~/.local/share/com.github.louis77.tuner/favorites.json`, that depends on `XDG_DATA_HOME` env var

**Comment by technosf** [comment]
@ktr2022  - Still and issue on v1.5.*?

How is Tuner packaged on your system?
