### ISSUE TITLE
radio station from radio-browser not working: https://radios-ec.cdn.nedmedia.io/radios/ec-lametro.m3u8

### ISSUE THREAD

**Issue by klascano** [louis77/tuner#84]
Hi, 

Great work with tuner.!

I cant play a radio station that i register in radio-browser "Radio MetroEC", however, also register another radio station and it's working "Radio Alegriarm".

![image](https://user-images.githubusercontent.com/5074068/159505137-cb56f5e9-079d-490a-a819-2b1b734450ed.png)

![image](https://user-images.githubusercontent.com/5074068/159505276-d93e28b7-4f06-4a52-a750-5fd06486dce7.png)

![image](https://user-images.githubusercontent.com/5074068/159505315-e60de345-bc3a-41f5-a212-ae60aa04a142.png)

I use tunner as flatpak in ubuntu 21.10.

Thanks.

**Comment by louis77** [comment]
Hi @klascano 

I've checked the station and it looks like radio-browser.info doesn't resolve the playlist URL to a playable stream. Tuner doesn't parse playlists and relies on the resolved URL. This is also why "UNKNOWN" is displayed as the codec.

Also the Favicon you have registered returns a HTTP 500 server error:
https://www.lametro.com.ec/wp-content/uploads/sites/12/2021/10/logo-lametro.png

I'll open an issue on the radiobrowser repo, let's see what the maintainer says about it.

Curious, the Tuner app icon I see in your screenshot looks completely different from the original tuner icon. Do you use any special theme?

**Comment by klascano** [comment]
thanks for your reply louis, again tuner is great!.

indeed, radio-browser can reproduce the stream but something happen in tuner or radio-browser, so i'll wait some response.

The icon is from papirus icon theme, gnome arc theme and flatpak version.

**Comment by louis77** [comment]
Alex from radio-browser explained the issue here:
https://github.com/segler-alex/radiobrowser-api-rust/issues/145#issuecomment-1075686000

So, obviously we have to make Tuner able to resolve these URLs directly. I'll keep this issue open and put it on the roadmap.
