### ISSUE TITLE
Online Translation Integration

### ISSUE THREAD

**Issue by libreajans** [louis77/tuner#85]
Hi, I have just discovered Tuner. It's a good app to listen Online Radios.

Could you intagrate weblate (https://hosted.weblate.org) or someting similar online translation service to your app?

It's not easy to send a Merge Request for every translation.

**Comment by louis77** [comment]
Hi @libreajans 
Thank you for this good suggestion. I've created a project on Weblate for Tuner:

https://hosted.weblate.org/projects/tuner

**Comment by libreajans** [comment]
Thank. I already complated Turkish translation.
