### ISSUE TITLE
DBUS: MPRIS: Metadata `xesam:title` hardcoded to `Tuner` instead of showing title from radio station

### ISSUE THREAD

**Issue by actionless** [louis77/tuner#97]
normally it should contain same info as displayed on the second line of the headerbar of the app, ie currently playing song/radioshow (it means title of the song, not title of the audio-player)

**Comment by louis77** [comment]
For reference:
https://github.com/louis77/tuner/blob/master/src/Services/DBusMediaPlayer.vala#L205

**Comment by louis77** [comment]
![Screenshot from 2022-12-16 11-15-42](https://user-images.githubusercontent.com/1240462/208076365-81f70dac-dbe8-490b-ab9c-57ecb1ed0c3a.png)

**Comment by technosf** [comment]
Shows title if there is one, otherwise station name.
